### ISSUE TITLE
Patrice's Tasks 1/16/23 - 1/20/23

### ISSUE THREAD

**Issue by natt96z** [natt96z/cybersac#17]
Comment and click "close issue" when Milestone/Issue is fixed

**Comment by computerbluerain** [comment]
"I downloaded the linux and ubuntu iso for VMWare player, downloading the software took longer than expected but is near completion" (1/16/23)

**Comment by computerbluerain** [comment]
"The team as whole helped set up virtual machines for all 3 team members" (1/17/23)

**Comment by computerbluerain** [comment]
"The team assisted in the Ubuntu downloading." (1/17/23)
"I reviewed the SOP and discussed any issues". (1/17/23)
"Windows 10 was downloaded onto my laptop." (1/18/23)
"The Ubuntu download is completed. I enabled the Hyper-V setting." (1/18/23)
"I worked on the documentation EasyPatriot spell-check and grammar." (1/18/23)
"The team, as a whole, setup iFrames." (1/18/23)
"The team reviewed the SOP's, ensured we all have completed VM's, and spellchecks are completed for this week." (1/19/23)

![WindowsSecurity](https://user-images.githubusercontent.com/116924471/213617690-07a8c434-27a3-46af-ad1d-f95869362e04.jpg)
![WindowsSecurityContinued](https://user-images.githubusercontent.com/116924471/213617721-ece63778-efdc-4b54-a356-32ebde9693c0.jpeg)
![iFrames](https://user-images.githubusercontent.com/116924471/213617781-187421ca-0630-4ab2-9c2c-c8839e1f23c8.jpeg)
![UbuntuDownload](https://user-images.githubusercontent.com/116924471/213615400-f5b1c47c-5c4a-40be-8f65-3bf0f6a9f91a.JPG)

**Comment by computerbluerain** [comment]
"I worked on the documentation EasyPatriot spell-check and grammar." (1/18/23)
"Line 48 - Added the word "are."
"Line 60 - Comma changed to a hyphen "-."
"Line 62 - Added the word "a" to "the virus executes "a" malicious code."
"Line 64 - Comma added "websites "," the user."
"Line 66 - Commas added "in,", "otherwise "," legitimate
"Line 74 - Comma added - "typically "," by overwriting data."
"Line 76 - Comma added - detection"," yet "," retain."

![BeginnerEasyCybersac rst](https://user-images.githubusercontent.com/116924471/213620230-a8572cff-6c1d-4c45-94ee-cffc690e8645.jpeg)
![BeginnerEasyCybersac rstContinued](https://user-images.githubusercontent.com/116924471/213620274-276c6950-1a2a-46fa-9e0c-626cc90006e0.jpeg)

**Comment by computerbluerain** [comment]
"I worked on the documentation EasyPatriot spell-check and grammar." (1/19/23)
"Line 60 - Placed BOLD on the word "Viruses."

![BeginnerEasyCybersac rstForLine60](https://user-images.githubusercontent.com/116924471/213621820-3e2b7db7-71d4-471e-bfe6-dcdf16ddb909.jpeg)
